project:
  type: website
  output-dir: docs

website:
  title: "LEMCA"
  navbar:
    left:
      - href: index.qmd
        text: Overview
  favicon: favicon.ico


format:
  html:
    theme: [cosmo, distill.scss]
    css: styles.css
    toc: true

