project:
  type: website
  output-dir: docs
  resources:
    - tasks/assets/**
    - designs/**

website:
  title: "LEMCA"
  navbar:
    left:
      - href: tasks/overview.qmd
        text: Tasks
      - href: designs.qmd
        text: Best Designs
  favicon: favicon.ico


format:
  html:
    theme: [cosmo, distill.scss]
    css: styles.css
    toc: true
    include-in-header: _macros.html
