project:
  type: website
  output-dir: docs

website:
  title: "LEMCA"
  navbar:
    left:
      - href: tasks/overview.qmd
        text: Tasks
      - href: designs.qmd
        text: Best Designs
      - href: dashboard-PR.qmd
        text: PR-Dashboard
  favicon: favicon.ico


format:
  html:
    theme: [cosmo, distill.scss]
    css: styles.css
    toc: true
