---
title: "LEMCA: LLM-Guided Synthesis of Efficient Mode-Switching Control Architectures"
---

## Abstract
::: {style="text-align: justify;"}
Physical control tasks in the natural world, such as driving or object manipulation, frequently exhibit dramatic variations in sensory and compute complexity over time. Correspondingly, a natural resource-efficient choice for robot control is to dynamically switch between control modes with varying resource allocations. However, such “mode-switching controllers” (MSCs) have historically required laborious, expert-driven design and synthesis for each new task. Driven by these design difficulties, modern robotic control architectures often fall back to a wasteful “monolithic” one-size-fits-all structure, where resource allocation is permanently anchored to the hardest, most resource-intensive task phases. To facilitate the design of performant yet efficient MSCs, we propose LLM-Guided synthesis of Efficient Mode-Switching Control Architectures (LEMCA). LEMCA represents MSC designs as interpretable programs to be iteratively refined in an evolutionary loop. To evaluate design fitness, we propose MSC-compatible extensions of automated controller synthesis approaches, such as reinforcement learning in simulation. LEMCA then leverages the semantic priors, reasoning, and coding capabilities of Large Language Models (LLMs) to iteratively edit controller modes, their corresponding sensory-compute resource allocations, and mode transitions. Our experiments across diverse control benchmarks show that LEMCA consistently discovers strategies that surpass the Pareto frontier of monolithic designs by reclaiming wasted resources during “easy” task phases. LEMCA thus presents an automated, low-effort path to synthesize resource-efficient MSC designs.
:::
### Links
<a href="/" class="btn btn-primary disabled" role="button">Paper</a>
<a href="/" class="btn btn-primary disabled" role="button">OpenReview</a>
<a href="/" class="btn btn-primary disabled" role="button">Code</a>

## Supplementary Material
The supplementary material is organized as follows, please click on the links below to navigate to the corresponding sections:

- [**Task Description**](tasks/overview.qmd)
  <br/>_Provides an overview of the following tasks LEMCA is evaluated on. The details of the task dynamics, sensor library, and associated costs are provided. See more at [link](tasks/overview.qmd)._
  + [`point-to-disk`](tasks/overview.qmd#point-to-disk)
  + [`RF-DMC`](tasks/overview.qmd#rf-dmc)
    * `cartpole-swingup`
    * `cup-catch`
    * `finger-spin`
  + [`clutter-nav`](tasks/overview.qmd#clutter-nav)
- [**Best Designs**](designs.qmd)
  <br/>_This presents an interactive dashboard to via the best mode-switching controller designs synthesized by LEMCA for each task + performance target. The dashboard outlines the source code of the best design along with its performance metrics and rollouts. View the dashboard at [link](designs.qmd)._
